#!/usr/bin/env bash

ls "$HOME/.local/share/rofi/themes/"
echo -n "Enter theme: "
read theme
# change this variable to the theme you prefer
#theme="default/default"

theme_dir="~/.local/share/rofi/themes/$theme/style.rasi"

rofi \
    -show drun \
    -terminal $term \
    -kb-cancel Escape \
    -theme $theme_dir
