# laptop
# monitor1: desc:AccuScene Corporation Ltd ASL 4K 0x04867576
# monitor2: desc:Dell Inc. DELL U2412M YPPY068M20LS

# Laptop monitor: disable if lid is closed

monitor=eDP-1,disable
monitor=desc:Dell Inc. DELL U2412M YPPY068M21QS,1920x1200@60,0x0,1.0,transform,0,vrr,0
monitor=desc:Dell Inc. DELL U2412M YPPY068M20LS,1920x1200@60,1920x0,1.0,transform,0,vrr,0

