# configuration for using with work super widescreen
# laptop placed to the LEFT
# - auto-disable laptop screen if lid closed

# isable laptop screen, use external only

monitor=eDP-1,disable

monitor=desc:LG Electronics LG HDR DQHD 0x0003D55F,preferred,auto-right,1.0

