# Files and directories #######################################################

music_directory "~/Music"

playlist_directory "~/.config/mpd/playlists"

db_file "~/.config/mpd/database"

state_file "~/.config/mpd/state"

# This is a database which manages dynamic information attached to songs.
# e.g. like, rating
sticker_file "~/.config/mpd/sticker.sql"

# General music daemon options ################################################

# "notice", "info", "verbose", "warning", "error"
#log_level	"notice"

# Setting "restore_paused" to "yes" puts MPD into pause mode instead
# of starting playback after startup. --> this restores the last playlist
restore_paused "yes"

# create playlists in a format usable by other music players
save_absolute_paths_in_playlists	"yes"

# enable automatic update of MPD's database when files in
# music_directory are changed.
auto_update	"yes"
#auto_update_depth "3"

# Input #######################################################################
#
input {
	plugin "curl"
}

# Replaygain ##################################
# "off", "album", "track", "auto".
# "auto": chooses between "track" and "album" depending on state of random playback.
# If random playback is enabled then "track" mode is used.
replaygain "track"

# Character Encoding ##########################################################
#
filesystem_charset		"UTF-8"

# Audio Output ################################################################
#
# MPD supports various audio output types, as well as playing through multiple
# audio outputs at the same time, through multiple audio_output settings
# blocks.
#
# default output
audio_output {
	type		"pipewire"
	name		"PipeWire Sound Server"
}
# cava
audio_output {
	type "fifo"
	name "cava_fifo"
	path "/tmp/mpd.fifo"
	format "44100:16:2"
}
