# idle lock manager
exec-once = hypridle
# quickshell: noctalia-shell
exec-once = qs -c noctalia-shell
# use kwallet for secrets
exec-once = /usr/lib/pam_kwallet_init
# auto-mounting manager
exec-once = udiskie
# japanese input with fcitx and mozc
exec-once = fcitx5
# tray applet network manager
exec-once = nm-online -q -s -x  && nm-applet
# somehow it's dead after reboot?
exec-once = systemctl --user start hyprdynamicmonitors.service
# wallpaper manager
#exec-once = hyprpaper
# plugin manager
#exec-once = hyprpm reload -n
# notification daemon
#exec-once = dunst
