# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 10
    rounding_power = 2

    border_part_of_window = false

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    # dim unfocused windows
    dim_inactive = false
    dim_strength = 0.2

    shadow {
        enabled = true
        # color = rgba($crustAlphaee)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
    }
}

# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = true
    workspace_wraparound = true
}

